"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { chooseSurface, correlatedDrift, decayWetness, impactProfile, type RainSurface } from "./rain-engine";

type Drop = { x:number; y:number; vx:number; vy:number; size:number; length:number; alpha:number };
type Splash = { x:number; y:number; age:number; life:number; size:number; surface:RainSurface };
type Leak = { x:number; y:number; life:number };
type Settings = {
  rainRate:number; intermittency:number; stormMemory:number; dropSize:number; sizeScatter:number; gravity:number;
  wind:number; gust:number; windMemory:number; turbulence:number;
  bucket:number; gutter:number; heater:number; puddle:number; wetMemory:number; wetPitch:number; splash:number; slosh:number;
  cavity:number; detune:number; resonance:number; slatCount:number; slatCoupling:number; spring:number; delay:number; feedback:number; wow:number; mutation:number;
  dropLevel:number; windLevel:number; rumble:number; stereo:number; chirp:number; master:number;
  persistence:number; streak:number; spectroGain:number; field:number; glow:number; lightning:number;
};
type SliderSpec = { key:keyof Settings; label:string; min:number; max:number; step:number; suffix?:string };

const DEFAULTS: Settings = { rainRate:46,intermittency:.58,stormMemory:9,dropSize:1.05,sizeScatter:.72,gravity:1,wind:.12,gust:.85,windMemory:4.8,turbulence:.55,bucket:.9,gutter:.7,heater:1.15,puddle:.5,wetMemory:7.5,wetPitch:.34,splash:1.05,slosh:.72,cavity:330,detune:.31,resonance:1.25,slatCount:72,slatCoupling:.68,spring:2.4,delay:.27,feedback:.44,wow:.018,mutation:.62,dropLevel:.62,windLevel:.24,rumble:.08,stereo:.82,chirp:.67,master:.72,persistence:.24,streak:17,spectroGain:1.5,field:.36,glow:.72,lightning:.08 };
const GROUPS: Array<{ title:string; controls:SliderSpec[] }> = [
  { title:"Weather generator", controls:[{key:"rainRate",label:"Mean rainfall",min:0,max:180,step:1,suffix:" /s"},{key:"intermittency",label:"Storm intermittency",min:0,max:1.8,step:.01},{key:"stormMemory",label:"Storm correlation",min:.2,max:40,step:.1,suffix:" s"},{key:"dropSize",label:"Mean drop size",min:.2,max:3,step:.01},{key:"sizeScatter",label:"Drop variance",min:0,max:2,step:.01},{key:"gravity",label:"Gravity / fall",min:.1,max:2.4,step:.01},{key:"wind",label:"Mean wind",min:-2,max:2,step:.01},{key:"gust",label:"Gust strength",min:0,max:3,step:.01},{key:"windMemory",label:"Wind correlation",min:.1,max:24,step:.1,suffix:" s"},{key:"turbulence",label:"Turbulent curl",min:0,max:2.5,step:.01}]},
  { title:"Impact routing / wet memory", controls:[{key:"bucket",label:"Bucket send",min:0,max:2,step:.01},{key:"gutter",label:"Gutter send",min:0,max:2,step:.01},{key:"heater",label:"Heater send",min:0,max:2,step:.01},{key:"puddle",label:"Puddle send",min:0,max:2,step:.01},{key:"wetMemory",label:"Wet-surface memory",min:.1,max:30,step:.1,suffix:" s"},{key:"wetPitch",label:"Wet pitch migration",min:-1,max:1,step:.01},{key:"splash",label:"Splash energy",min:0,max:2.5,step:.01},{key:"slosh",label:"Liquid boundary motion",min:0,max:2,step:.01}]},
  { title:"Resonance without agreement", controls:[{key:"cavity",label:"Cavity center",min:45,max:1400,step:1,suffix:" Hz"},{key:"detune",label:"Resonator disagreement",min:0,max:1.5,step:.01},{key:"resonance",label:"Cavity Q",min:.1,max:4,step:.01},{key:"slatCount",label:"Heater slats",min:8,max:160,step:1},{key:"slatCoupling",label:"Slat energy leakage",min:0,max:1.5,step:.01},{key:"spring",label:"Spring reverb",min:.05,max:6,step:.01,suffix:" s"},{key:"delay",label:"Tape delay",min:.025,max:1.2,step:.001,suffix:" s"},{key:"feedback",label:"Tape feedback",min:0,max:.88,step:.01},{key:"wow",label:"Tape wow / flutter",min:0,max:.12,step:.001},{key:"mutation",label:"Topology mutation",min:0,max:4,step:.01,suffix:" /s"}]},
  { title:"The Machine / listening chain", controls:[{key:"dropLevel",label:"Droplet voice",min:0,max:1.5,step:.01},{key:"windLevel",label:"Wind voice",min:0,max:1.2,step:.01},{key:"rumble",label:"Structure-borne rumble",min:0,max:1,step:.01},{key:"stereo",label:"Room width",min:0,max:1,step:.01},{key:"chirp",label:"Plink ↔ plunk articulation",min:0,max:1,step:.01},{key:"master",label:"Master",min:0,max:1,step:.01}]},
  { title:"Oscilloscope rain", controls:[{key:"persistence",label:"Retinal persistence",min:.02,max:.94,step:.01},{key:"streak",label:"Drop streak",min:2,max:42,step:1},{key:"spectroGain",label:"Spectrograph gain",min:.2,max:5,step:.01},{key:"field",label:"Wind field visibility",min:0,max:1,step:.01},{key:"glow",label:"Heater glow",min:0,max:1.5,step:.01},{key:"lightning",label:"Electrical weather",min:0,max:1,step:.01}]},
];
const PRESETS: Record<string,Partial<Settings>> = {
  "Almost Rain":{}, "Bucket Survey":{rainRate:27,bucket:2,gutter:.08,heater:.12,puddle:.15,cavity:244,slosh:1.35,delay:.38,feedback:.58}, "Bad Gutter":{rainRate:62,intermittency:1.2,gutter:2,bucket:.1,heater:.25,wind:1.15,gust:1.8,turbulence:1.3}, "Heater Floor":{rainRate:38,heater:2,bucket:.15,gutter:.45,puddle:.2,slatCount:128,slatCoupling:1.2,spring:4.4,cavity:512}, "Muggy Downpour":{rainRate:138,intermittency:.92,stormMemory:16,wind:.22,gust:.48,wetMemory:24,puddle:1.5,rumble:.24,persistence:.56}, "Weather Arrives":{rainRate:96,intermittency:1.55,stormMemory:5.5,sizeScatter:1.5,gust:2.4,turbulence:1.8,wetMemory:17,slosh:1.7,detune:1.05,mutation:2.6,wow:.072,feedback:.67,field:.72,lightning:.42},
};
const SURFACE_COLOR:Record<RainSurface,string>={bucket:"#5fd6ff",gutter:"#8cffd2",heater:"#ffd65d",puddle:"#b282ff"};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));

function Slider({ spec, value, onChange }:{spec:SliderSpec;value:number;onChange:(value:number)=>void}) { const decimals=spec.step<.01?3:spec.step<1?2:0; return <label className="rain-slider"><span>{spec.label}<output>{value.toFixed(decimals)}{spec.suffix??""}</output></span><input type="range" min={spec.min} max={spec.max} step={spec.step} value={value} onChange={e=>onChange(+e.target.value)}/></label>; }

export function RainRoom(){
  const canvasRef=useRef<HTMLCanvasElement>(null);const settingsRef=useRef(DEFAULTS);const dropsRef=useRef<Drop[]>([]);const splashesRef=useRef<Splash[]>([]);const leaksRef=useRef<Leak[]>([]);const wetRef=useRef<Record<RainSurface,number>>({bucket:0,gutter:0,heater:0,puddle:0});const stormRef=useRef(1);const windRef=useRef(0);const mutationRef=useRef(0);const frameRef=useRef(0);const pausedRef=useRef(false);
  const audioRef=useRef<AudioContext|null>(null);const masterRef=useRef<GainNode|null>(null);const impactRef=useRef<GainNode|null>(null);const windGainRef=useRef<GainNode|null>(null);const rumbleGainRef=useRef<GainNode|null>(null);const delayRef=useRef<DelayNode|null>(null);const feedbackRef=useRef<GainNode|null>(null);const analyserRef=useRef<AnalyserNode|null>(null);const audioStartedRef=useRef(false);const spectralRef=useRef<HTMLCanvasElement|null>(null);
  const [settings,setSettings]=useState(DEFAULTS);const [paused,setPaused]=useState(false);const [audioOn,setAudioOn]=useState(false);const [hidden,setHidden]=useState(false);const [preset,setPreset]=useState("Almost Rain");const [status,setStatus]=useState({storm:1,wind:0,wet:0,drops:0,dominant:"puddle" as RainSurface});
  useEffect(()=>{settingsRef.current=settings;if(masterRef.current)masterRef.current.gain.setTargetAtTime(settings.master,audioRef.current?.currentTime??0,.03);if(windGainRef.current)windGainRef.current.gain.setTargetAtTime(settings.windLevel*.18,audioRef.current?.currentTime??0,.1);if(rumbleGainRef.current)rumbleGainRef.current.gain.setTargetAtTime(settings.rumble*.09,audioRef.current?.currentTime??0,.1);if(feedbackRef.current)feedbackRef.current.gain.setTargetAtTime(settings.feedback,audioRef.current?.currentTime??0,.05);},[settings]);useEffect(()=>{pausedRef.current=paused},[paused]);
  const bootAudio=useCallback(async()=>{if(!audioRef.current){const ctx=new AudioContext();audioRef.current=ctx;const master=ctx.createGain(),impact=ctx.createGain(),analyser=ctx.createAnalyser(),delay=ctx.createDelay(1.5),feedback=ctx.createGain();analyser.fftSize=512;analyser.smoothingTimeConstant=.66;master.gain.value=settingsRef.current.master;delay.delayTime.value=settingsRef.current.delay;feedback.gain.value=settingsRef.current.feedback;impact.connect(master);impact.connect(delay);delay.connect(feedback).connect(delay);delay.connect(master);master.connect(analyser).connect(ctx.destination);masterRef.current=master;impactRef.current=impact;delayRef.current=delay;feedbackRef.current=feedback;analyserRef.current=analyser;
      const noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate),data=noiseBuffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+(Math.random()*2-1)*.08)/1.08;data[i]=brown*3;}const noise=ctx.createBufferSource(),windFilter=ctx.createBiquadFilter(),windGain=ctx.createGain();noise.buffer=noiseBuffer;noise.loop=true;windFilter.type="bandpass";windFilter.frequency.value=650;windFilter.Q.value=.42;windGain.gain.value=settingsRef.current.windLevel*.18;noise.connect(windFilter).connect(windGain).connect(master);noise.start();windGainRef.current=windGain;
      const rumble=ctx.createOscillator(),rumbleGain=ctx.createGain();rumble.type="sine";rumble.frequency.value=38;rumbleGain.gain.value=settingsRef.current.rumble*.09;rumble.connect(rumbleGain).connect(master);rumble.start();rumbleGainRef.current=rumbleGain;audioStartedRef.current=true;}await audioRef.current.resume();setAudioOn(true);},[]);
  const impactSound=useCallback((surface:RainSurface,size:number,x:number)=>{const ctx=audioRef.current,bus=impactRef.current;if(!ctx||!bus||!audioStartedRef.current)return;const s=settingsRef.current,wet=wetRef.current[surface],profile=impactProfile(surface,size,wet,s.cavity,s.wetPitch);const now=ctx.currentTime+.006,panner=ctx.createStereoPanner(),gain=ctx.createGain(),osc=ctx.createOscillator();panner.pan.value=clamp((x*2-1)*s.stereo,-1,1);osc.type=surface==="heater"?"triangle":"sine";const direction=s.chirp;const start=profile.startHz*(1-direction*.25),end=profile.endHz*(.72+direction*.55);osc.frequency.setValueAtTime(clamp(start,25,12000),now);osc.frequency.exponentialRampToValueAtTime(clamp(end,25,12000),now+profile.decay);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,s.dropLevel*.08*size),now+.003);gain.gain.exponentialRampToValueAtTime(.0001,now+profile.decay*(.7+s.spring*.16));osc.connect(gain).connect(panner).connect(bus);osc.start(now);osc.stop(now+Math.min(3,profile.decay*(1+s.spring*.25))+.05);
    const count=surface==="heater"?2:1;for(let k=0;k<count;k++){const partial=ctx.createOscillator(),partialGain=ctx.createGain();partial.type="sine";partial.frequency.value=clamp(profile.endHz*(1.6+k*.77+s.detune*(Math.random()-.5)),40,14000);partialGain.gain.setValueAtTime(s.dropLevel*.025*profile.resonance,now);partialGain.gain.exponentialRampToValueAtTime(.0001,now+profile.decay*(1+s.slatCoupling));partial.connect(partialGain).connect(panner);partial.start(now);partial.stop(now+Math.min(4,profile.decay*(1+s.slatCoupling))+.02);}
    if(profile.noise>0){const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.075),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*6);const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),ng=ctx.createGain();filter.type="highpass";filter.frequency.value=900;ng.gain.value=s.dropLevel*.035*profile.noise*s.splash;src.buffer=buffer;src.connect(filter).connect(ng).connect(panner);src.start(now);}
  },[]);
  const strike=useCallback((x:number,y:number,size:number)=>{const s=settingsRef.current;const surface=chooseSurface(Math.random(),{bucket:s.bucket,gutter:s.gutter,heater:s.heater,puddle:s.puddle});wetRef.current[surface]=decayWetness(wetRef.current[surface],s.wetMemory,0,.025*size);splashesRef.current.push({x,y,age:0,life:.18+s.splash*.22,size:size*(.6+s.splash),surface});if(splashesRef.current.length>360)splashesRef.current.splice(0,40);const sonicBudget=Math.min(1,70/Math.max(1,s.rainRate*stormRef.current));if(Math.random()<sonicBudget)impactSound(surface,size,x);},[impactSound]);
  const randomize=()=>{const next={...settings};for(const group of GROUPS)for(const control of group.controls){const u=Math.random(),biased=control.key==="rainRate"?Math.pow(u,.55):u;(next[control.key] as number)=control.min+(control.max-control.min)*biased;}setSettings(next);setPreset("Unrepeatable patch");};
  const loadPreset=(name:string)=>{setSettings({...DEFAULTS,...PRESETS[name]});setPreset(name);};
  const toggleAudio=async()=>{if(!audioOn)await bootAudio();else{await audioRef.current?.suspend();setAudioOn(false)}};
  useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const context=canvas.getContext("2d");if(!context)return;let last=performance.now(),animation=0;if(!spectralRef.current){spectralRef.current=document.createElement("canvas");spectralRef.current.width=240;spectralRef.current.height=110;}
    const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));context.setTransform(d,0,0,d,0,0)};resize();addEventListener("resize",resize);
    const draw=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;const s=settingsRef.current,w=canvas.clientWidth,h=canvas.clientHeight;stormRef.current=clamp(correlatedDrift(stormRef.current,1,s.stormMemory,dt,(Math.random()*2-1),s.intermittency),0,3.2);windRef.current=correlatedDrift(windRef.current,s.wind,s.windMemory,dt,(Math.random()*2-1),s.gust);mutationRef.current=Math.max(0,mutationRef.current-dt);if(Math.random()<s.mutation*dt){mutationRef.current=.18+Math.random()*.65;windRef.current+=(Math.random()*2-1)*s.turbulence;}
      for(const surface of Object.keys(wetRef.current) as RainSurface[])wetRef.current[surface]=decayWetness(wetRef.current[surface],s.wetMemory,dt);
      if(!pausedRef.current){let spawn=Math.min(55,s.rainRate*stormRef.current*dt);for(const leak of leaksRef.current){leak.life-=dt;spawn+=Math.max(0,leak.life)*8;}while(spawn>Math.random()){const leak=leaksRef.current.length&&Math.random()<.18?leaksRef.current[Math.floor(Math.random()*leaksRef.current.length)]:null;const size=Math.max(.18,s.dropSize+(Math.random()*2-1)*s.sizeScatter);dropsRef.current.push({x:leak?clamp(leak.x+(Math.random()-.5)*.035,0,1):Math.random(),y:leak?leak.y:Math.random()*.05-.08,vx:windRef.current*.03+(Math.random()-.5)*s.turbulence*.012,vy:.05+Math.random()*.08,size,length:s.streak*(.6+Math.random()*.8),alpha:.42+Math.random()*.5});spawn--;}
        leaksRef.current=leaksRef.current.filter(leak=>leak.life>0);for(const drop of dropsRef.current){const curl=Math.sin(drop.y*18+now*.0017+drop.x*9)*s.turbulence*.006;drop.vx+=(windRef.current*.018+curl-drop.vx*.6)*dt;drop.vy+=.7*s.gravity*dt;drop.x+=drop.vx*dt;drop.y+=drop.vy*dt;if(drop.x<-.06)drop.x=1.05;if(drop.x>1.06)drop.x=-.05;if(drop.y>=.91){strike(clamp(drop.x,0,1),.91,drop.size);drop.y=2;}}dropsRef.current=dropsRef.current.filter(drop=>drop.y<1.1).slice(-1800);for(const splash of splashesRef.current)splash.age+=dt;splashesRef.current=splashesRef.current.filter(x=>x.age<x.life);}
      if(delayRef.current&&audioRef.current){delayRef.current.delayTime.setTargetAtTime(clamp(s.delay*(1+Math.sin(now*.0043)*s.wow*7+wetRef.current.bucket*s.slosh*.08),.01,1.45),audioRef.current.currentTime,.04);if(windGainRef.current)windGainRef.current.gain.setTargetAtTime(s.windLevel*.12*(.35+stormRef.current*.65),audioRef.current.currentTime,.08);}
      context.fillStyle=`rgba(4,9,18,${clamp(1-s.persistence,.045,.98)})`;context.fillRect(0,0,w,h);const flash=Math.random()<s.lightning*stormRef.current*dt*.15; if(flash){context.fillStyle=`rgba(190,220,255,${.18+s.lightning*.3})`;context.fillRect(0,0,w,h);}
      const wetAvg=Object.values(wetRef.current).reduce((a,b)=>a+b,0)/4;context.fillStyle="rgba(15,29,40,.82)";context.fillRect(0,0,w,h);const windowW=w*.59;context.fillStyle="#08131f";context.fillRect(0,0,windowW,h*.74);context.strokeStyle=`rgba(86,185,216,${.09+s.field*.25})`;context.lineWidth=1;for(let y=30;y<h*.72;y+=46)for(let x=28;x<windowW;x+=58){const a=windRef.current*.32+Math.sin(x*.013+y*.019+now*.001)*s.turbulence*.25;context.beginPath();context.moveTo(x,y);context.lineTo(x+Math.cos(a)*18*s.field,y+Math.sin(a)*18*s.field);context.stroke();}
      context.fillStyle="#1b2529";context.fillRect(windowW,0,w-windowW,h);context.fillStyle=`rgba(255,185,70,${.035+s.glow*.08+wetRef.current.heater*.025})`;context.fillRect(windowW+12,h*.09,w-windowW-24,h*.78);const slats=Math.min(160,Math.round(s.slatCount));context.strokeStyle=`rgba(215,226,206,${.18+s.glow*.34})`;context.lineWidth=Math.max(1,(w-windowW-35)/slats*.35);for(let i=0;i<slats;i++){const x=windowW+18+i/slats*(w-windowW-38),wave=Math.sin(i*.73+now*.002*(1+s.slatCoupling))*mutationRef.current*12;context.beginPath();context.moveTo(x,h*.12+wave);context.lineTo(x,h*.84-wave);context.stroke();}
      context.strokeStyle="#89a7ad";context.lineWidth=6;context.beginPath();context.moveTo(0,h*.17);context.lineTo(windowW*.82,h*.17);context.lineTo(windowW*.92,h*.25);context.stroke();context.fillStyle="#172329";context.beginPath();context.ellipse(w*.2,h*.87,w*.09,h*.08,0,0,Math.PI*2);context.fill();context.strokeStyle="#6dcce5";context.lineWidth=2;context.stroke();context.fillStyle=`rgba(74,159,190,${.28+clamp(wetRef.current.bucket,0,.6)})`;context.beginPath();context.ellipse(w*.2,h*.85,w*.074,h*.025,0,0,Math.PI*2);context.fill();context.fillStyle=`rgba(57,96,123,${.25+clamp(wetRef.current.puddle,0,.45)})`;context.beginPath();context.ellipse(w*.47,h*.93,w*.25,h*.035,0,0,Math.PI*2);context.fill();
      context.strokeStyle="#9ae7ff";context.lineCap="round";for(const drop of dropsRef.current){context.globalAlpha=drop.alpha;context.lineWidth=Math.max(.6,drop.size*.72);context.beginPath();context.moveTo(drop.x*w,drop.y*h);context.lineTo(drop.x*w-drop.vx*s.streak*8,drop.y*h-drop.length);context.stroke();}context.globalAlpha=1;for(const splash of splashesRef.current){const a=1-splash.age/splash.life;context.strokeStyle=SURFACE_COLOR[splash.surface];context.globalAlpha=a*.8;context.lineWidth=1;for(let j=0;j<4;j++){const angle=-Math.PI*.85+j/3*Math.PI*.7+(splash.x-.5)*.2;const r=splash.size*17*(1-a);context.beginPath();context.moveTo(splash.x*w,splash.y*h);context.lineTo(splash.x*w+Math.cos(angle)*r,splash.y*h+Math.sin(angle)*r);context.stroke();}}context.globalAlpha=1;
      const spectral=spectralRef.current!,sg=spectral.getContext("2d")!;sg.drawImage(spectral,-1,0);sg.fillStyle="#020408";sg.fillRect(spectral.width-1,0,1,spectral.height);if(analyserRef.current){const bins=new Uint8Array(analyserRef.current.frequencyBinCount);analyserRef.current.getByteFrequencyData(bins);for(let y=0;y<spectral.height;y++){const index=Math.floor(Math.pow(1-y/spectral.height,2)*bins.length);const level=clamp(bins[index]/255*s.spectroGain,0,1);sg.fillStyle=`hsl(${190-level*145} 95% ${8+level*67}%)`;sg.fillRect(spectral.width-1,y,1,1);}}context.globalAlpha=.86;context.drawImage(spectral,18,h-132,240,110);context.globalAlpha=1;context.strokeStyle="rgba(180,232,244,.55)";context.strokeRect(18,h-132,240,110);context.fillStyle="#bcebf5";context.font="700 8px ui-monospace";context.fillText("LIVE SPECTROGRAPH / THE MACHINE RETURN",25,h-140);
      frameRef.current++;if(frameRef.current%12===0){const dominant=(Object.entries(wetRef.current) as Array<[RainSurface,number]>).sort((a,b)=>b[1]-a[1])[0][0];setStatus({storm:stormRef.current,wind:windRef.current,wet:wetAvg,drops:dropsRef.current.length,dominant});}animation=requestAnimationFrame(draw);};animation=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(animation);removeEventListener("resize",resize)};},[strike]);
  useEffect(()=>()=>{void audioRef.current?.close()},[]);
  const placeLeak=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();leaksRef.current.push({x:clamp((e.clientX-r.left)/r.width,.02,.98),y:clamp((e.clientY-r.top)/r.height,.03,.68),life:4+Math.random()*8});};
  return <main className={`rain-page${hidden?" controls-hidden":""}`}><button className="rain-ui-toggle" onClick={()=>setHidden(v=>!v)}>{hidden?"Return to The Machine":"Leave the controls in the house"}</button><header className="rain-head"><Link href="/gallery">← Gallery</Link><div><span className="eyebrow">Interactive Exhibit 33 · Counterfeit Weather</span><h1>Do You Hear<br/>the Rain?</h1><p>A room, a bucket, a bad gutter, an incidental vibraphone—and several dozen patch cables trying to persuade noise that it is weather.</p></div><Link href="/compendium/tales-from-the-ruliad/the-machine-and-the-xaser#rain-log">Read the field log ↗</Link></header><section className="rain-console"><div className="rain-stage"><canvas ref={canvasRef} onPointerDown={placeLeak} aria-label="Interactive room filling with wind-driven rain, resonant impacts, buckets, gutters, heater slats, splashes, and a live spectrograph"/><div className="rain-telemetry"><span>STORM <b>{status.storm.toFixed(2)}</b></span><span>WIND <b>{status.wind.toFixed(2)}</b></span><span>WET MEMORY <b>{status.wet.toFixed(2)}</b></span><span>FIELD <b>{status.drops}</b></span><span>ARGUMENT <b>{status.dominant}</b></span></div><p>Tap anywhere to introduce a temporary leak.</p></div><aside className="rain-controls"><div className="rain-actions"><button className="primary" onClick={()=>void toggleAudio()}>{audioOn?"Silence circuitry":"Hear The Machine"}</button><button onClick={()=>setPaused(v=>!v)}>{paused?"Resume weather":"Pause weather"}</button><button onClick={randomize}>Repatch everything</button></div><div className="rain-presets">{Object.keys(PRESETS).map(name=><button className={preset===name?"active":""} key={name} onClick={()=>loadPreset(name)}>{name}</button>)}</div>{GROUPS.map((group,index)=><details key={group.title} open={index<2}><summary>{group.title}</summary><div className="rain-grid">{group.controls.map(spec=><Slider key={spec.key} spec={spec} value={settings[spec.key]} onChange={value=>{setSettings(current=>({...current,[spec.key]:value}));setPreset("Hand-patched")}}/>)}</div></details>)}<p className="rain-note">Sound begins only after <b>Hear The Machine</b>. Tap the room to make leaks. Wet surfaces retain imperfect memory, shifting resonances and delay time; topology mutations briefly push the heater slats and wind field out of agreement.</p></aside></section><footer className="rain-foot"><b>THE MACHINE / PRECIPITATION PATCH</b><p>This model is allowed to be proud of itself. The weather is allowed to arrive anyway.</p></footer></main>;
}
