"use client";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
type V=[number,number,number];
const norm=(a:V):V=>{const l=Math.hypot(...a)||1;return[a[0]/l,a[1]/l,a[2]/l]};
const cross=(a:V,b:V):V=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const add=(a:V,b:V):V=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
function Slider({label,value,set,min,max,step=1,suffix="°"}:any){return <label className="mirror-slider"><span>{label}<input type="number" value={Math.round(value*10)/10} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/>{suffix}</span><input aria-label={label} type="range" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>}
export function MirrorLab(){
  const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{x:number,y:number}|null>(null);const [elevation,setElevation]=useState(-42),[azimuth,setAzimuth]=useState(90),[viewYaw,setViewYaw]=useState(-34),[viewPitch,setViewPitch]=useState(22),[sweep,setSweep]=useState(false),[grid,setGrid]=useState(true);
  useEffect(()=>{let raf=0,t=0;const draw=()=>{const c=canvas.current;if(!c)return;const dpr=Math.min(devicePixelRatio,2),r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;const ctx=c.getContext("2d")!;ctx.scale(dpr,dpr);const w=r.width,h=r.height;ctx.fillStyle="#07141a";ctx.fillRect(0,0,w,h);
    const xi=(sweep?-70+70*(.5+.5*Math.sin(t*.018)):elevation)*Math.PI/180,az=azimuth*Math.PI/180;const input:V=[1,0,0],output:V=[Math.cos(xi)*Math.cos(az),Math.cos(xi)*Math.sin(az),Math.sin(xi)],normal=norm(add(input,output));let p1=norm(cross(normal,Math.abs(normal[2])<.8?[0,0,1]:[0,1,0])),p2=norm(cross(normal,p1));
    const yaw=viewYaw*Math.PI/180,pitch=viewPitch*Math.PI/180,project=(v:V,scale=1):[number,number]=>{const x=v[0]*Math.cos(yaw)-v[1]*Math.sin(yaw),z=v[2];return[w*.52+(x*scale)*Math.cos(pitch)*Math.min(w,h)*.28,h*.53+(x*scale)*Math.sin(pitch)*Math.min(w,h)*.28-(z*scale)*Math.min(w,h)*.28]};
    ctx.strokeStyle="rgba(186,218,220,.12)";ctx.lineWidth=1;if(grid)for(let i=-10;i<=10;i++){let a=project([i/10,-1,0]),b=project([i/10,1,0]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();a=project([-1,i/10,0]);b=project([1,i/10,0]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
    const corners:[number,number][]=[[-1,-1],[1,-1],[1,1],[-1,1]],pts=corners.map(([a,b])=>project([p1[0]*a*.58+p2[0]*b*.58,p1[1]*a*.58+p2[1]*b*.58,p1[2]*a*.58+p2[2]*b*.58]));ctx.fillStyle="rgba(195,220,218,.25)";ctx.strokeStyle="#d6e7e1";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(...pts[0]);pts.slice(1).forEach(q=>ctx.lineTo(...q));ctx.closePath();ctx.fill();ctx.stroke();
    for(let i=-4;i<=4;i++){const a=project([p1[0]*i*.12-p2[0]*.58,p1[1]*i*.12-p2[1]*.58,p1[2]*i*.12-p2[2]*.58]),b=project([p1[0]*i*.12+p2[0]*.58,p1[1]*i*.12+p2[1]*.58,p1[2]*i*.12+p2[2]*.58]);ctx.strokeStyle="rgba(220,240,235,.18)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}
    const arrow=(v:V,color:string,label:string,len=1)=>{const o=project([0,0,0]),q=project(v,len);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=4;ctx.shadowColor=color;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(...o);ctx.lineTo(...q);ctx.stroke();ctx.shadowBlur=0;ctx.beginPath();ctx.arc(q[0],q[1],6,0,Math.PI*2);ctx.fill();ctx.font="700 10px system-ui";ctx.fillText(label,q[0]+10,q[1]-8)};
    arrow(input,"#f05b44","INPUT");arrow(output,"#61e6b5","OUTPUT");arrow(normal,"#68aef4","NORMAL",.82);const proj=norm([normal[0],normal[1],0]);arrow(proj,"#e69be5","XY PROJECTION",.7);
    const cx=project([0,0,0]);ctx.fillStyle="#f4edda";ctx.beginPath();ctx.arc(cx[0],cx[1],5,0,Math.PI*2);ctx.fill();ctx.fillStyle="rgba(244,237,218,.65)";ctx.font="10px system-ui";ctx.fillText("DRAG FIELD TO ORBIT",18,h-20);t++;if(sweep)raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[elevation,azimuth,viewYaw,viewPitch,sweep,grid]);
  const xi=(sweep?elevation:elevation),er=xi*Math.PI/180,ar=azimuth*Math.PI/180,out:V=[Math.cos(er)*Math.cos(ar),Math.cos(er)*Math.sin(ar),Math.sin(er)],n=norm(add([1,0,0],out)),theta=Math.atan2(n[1],n[0])*180/Math.PI,phi=Math.asin(n[2])*180/Math.PI;
  return <main className="mirror-page"><header className="mirror-header"><Link className="back" href="/gallery">Gallery</Link><div><span className="eyebrow">Interactive Exhibit 12 · Geometric Optics</span><h1>Mirror Steering</h1></div><Link href="/compendium/mirror-steering">Read the field note →</Link></header>
    <section className="mirror-console"><div className="mirror-stage"><canvas ref={canvas} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;setViewYaw(v=>v+(e.clientX-drag.current!.x)*.35);setViewPitch(v=>Math.max(-80,Math.min(80,v+(e.clientY-drag.current!.y)*.25)));drag.current={x:e.clientX,y:e.clientY}}} onPointerUp={()=>drag.current=null}/><div className="mirror-readout"><span>θ <b>{theta.toFixed(1)}°</b></span><span>φ <b>{phi.toFixed(1)}°</b></span><span>ξ <b>{elevation.toFixed(1)}°</b></span></div></div>
      <aside className="mirror-controls"><p className="control-label">Outgoing beam</p><Slider label="Elevation ξ" value={elevation} set={setElevation} min={-89} max={89}/><Slider label="Azimuth" value={azimuth} set={setAzimuth} min={-180} max={180}/>
        <p className="control-label">Observer</p><Slider label="View yaw" value={viewYaw} set={setViewYaw} min={-180} max={180}/><Slider label="View pitch" value={viewPitch} set={setViewPitch} min={-80} max={80}/>
        <div className="mirror-actions"><button className={sweep?"active":""} onClick={()=>setSweep(v=>!v)}>{sweep?"Stop sweep":"Sweep output"}</button><button className={grid?"active":""} onClick={()=>setGrid(v=>!v)}>Ground grid</button></div>
        <div className="mirror-presets"><button onClick={()=>{setAzimuth(90);setElevation(0)}}>90° turn</button><button onClick={()=>{setAzimuth(90);setElevation(-45)}}>Dive −45°</button><button onClick={()=>{setAzimuth(135);setElevation(35)}}>Oblique</button></div>
        <p>The mirror normal bisects the unit vectors of the incoming and desired outgoing rays. Change the destination; the mirror finds its pose.</p></aside>
    </section></main>
}
