export const ARCHIVED_FORTUNES = [
  "An unexpected event will soon make your life more exciting.",
  "You shall soon make a long, overdue personal decision.",
  "Life is a series of choices. Today yours are good ones.",
  "Joy will come with the return of a good friend.",
  "Laughter is the shortest distance between two people.",
  "You are a deep thinker with a knack for problem solving.",
  "Things are not always what they seem. It's not that bad!",
  "More art in your life at this time will help you feel better.",
  "Everyday in your life is a special occasion.",
  "You will be sharing great news with all the people you love.",
  "You will have many friends when you need them.",
  "Playing safe is only playing.",
  "The smart thing is to prepare for the unexpected.",
  "Before the beginning of great brilliance, there must be chaos.",
  "Better aim at the moon than shoot into the well.",
  "If you are wise with your decisions, good things are bound to come.",
  "A person with a determined heart frightens problems away.",
  "A dream will always triumph over reality, once it is given a chance.",
  "You are what you do, not what you say.",
  "There will be plenty of time to work hard; enjoy yourself!",
  "Happiness isn't something you remember, it's something you experience.",
  "Respect for others is peace. Respect for yourself is happiness.",
  "A good home is happiness.",
  "Be sensitive, but not overly sensitive.",
  "Analyze only when necessary.",
  "Humor is best weapon against sarcasm. Laugh at it.",
  "Advice, when most needed, is least heeded.",
  "Your fate is in no one else but you, no other hands but yours.",
  "Today's preparation determines tomorrow's achievement.",
  "When one door closes, another will open.",
  "Avoid compulsively making things worse.",
  "You will soon receive an email of great importance.",
  "This coming Friday will be an exciting time for you.",
  "He who put face in fruit drink get punch in the nose.",
  "Warning!!! This product contains gluten.",
  "You will soon be receiving an important email.",
  "One cannot know the best that is in him.",
  "You are compassionate and fun-loving.",
  "Versatility is one of your outstanding traits.",
  "If you are never scared, embarassed or hurt, it means you never take chances.",
  "You take criticism as an opportunity to grow.",
  "You are guided by love and friendship.",
  "Be happy with the person you are, and don't let anyone tell you otherwise.",
] as const;
